account_id = ""
compatibility_date = "2024-06-19"
main = "./dist/worker.js"
name = "wrangler-d1-execute-potential-defect"

workers_dev = true

[env.dev]
name = "wrangler-d1-execute-potential-defect"
d1_databases = [
  { binding = "DB", database_name = "wrangler-d1-execute-potential-defect", database_id = "" }
]
